name: "Publish Release"

# The workflow below runs when the release event triggers with a Pull Request is closed and merged.
# For more information on the release event.
# See: [Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#release)
# See: https://localheinz.com/articles/2022/01/24/creating-releases-with-github-actions/

on: 
  pull_request:
    types:
      - closed

jobs:
  release-linux:
    # The the release job will only run if the pull request was also merged
    if: github.event.pull_request.merged == true
    name: "Publish Linux packages"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64
        goos: [linux]
        goarch: ["386", amd64, arm64]

    permissions:
      contents: write
      packages: write
      pull-requests: write

    steps:
    
      # See: https://github.com/marketplace/actions/checkout
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - uses: ./.github/actions/publish-package
        with:
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          extension: ""

  release-macos:
    # The the release job will only run if the pull request was also merged
    if: github.event.pull_request.merged == true
    name: "Publish macOS packages"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # build and publish in parallel: darwin/amd64, darwin/arm64
        goos: [darwin]
        goarch: [amd64, arm64]

    permissions:
      contents: write
      packages: write
      pull-requests: write

    steps:
    
      # See: https://github.com/marketplace/actions/checkout
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - uses: ./.github/actions/publish-package
        with:
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          extension: ""

  release-windows:
    # The the release job will only run if the pull request was also merged
    if: github.event.pull_request.merged == true
    name: "Publish Windows packages"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # build and publish in parallel: windows/386, windows/amd64
        goos: [windows]
        goarch: ["386", amd64]

    permissions:
      contents: write
      packages: write
      pull-requests: write

    steps:
    
      # See: https://github.com/marketplace/actions/checkout
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - uses: ./.github/actions/publish-package
        with:
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          extension: ".exe"
