name: "PR Test and coverage"

# The workflow below runs when the release event triggers on not merged Pull Requests.
# For more information on the release event.
# See: [Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request)

on:
  pull_request:

jobs:
  test-and-coverage:
    # The the release job will only run if the pull request is merged
    if: ${{ github.ref != 'refs/heads/main' && github.event.pull_request.merged != true }}
    name: "Tests for Pull Requests"
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
    
      # See: https://github.com/marketplace/actions/checkout
      - name: "Checkout repository"
        uses: actions/checkout@v3

      # See: https://github.com/marketplace/actions/actionlint-with-reviewdog
      # See: https://github.com/rhysd/actionlint
      - name: "Lint GitHub Action Workflows - Checks"
        uses: reviewdog/action-actionlint@v1
        with:
          reporter: github-pr-check
          fail_on_error: false

      # See: https://github.com/marketplace/actions/actionlint-with-reviewdog
      # See: https://github.com/rhysd/actionlint
      - name: "Lint GitHub Action Workflows - Reviews"
        uses: reviewdog/action-actionlint@v1
        with:
          actionlint_flags: -ignore "undefined variable \"vars\""
          reporter: github-pr-review

      # See: https://github.com/marketplace/actions/reviewdog-suggester-suggest-any-code-changes-based-on-diff-with-reviewdog
      - uses: reviewdog/action-suggester@v1

      - uses: ./.github/actions/ci
