name: "Update released versions"

# The workflow below runs when the release event triggers when tags are created.
# For more information on the release event.
# See: [Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#push)

on:
  push:
    branches-ignore:
      - '**'
    tags:
      - 'v*.*.*'

jobs:
  update-semver:
    runs-on: ubuntu-latest

    steps:

      # See: https://github.com/marketplace/actions/checkout
      - name: "Checkout repository"
        id: checkout_repository
        uses: actions/checkout@v3

      # See: https://github.com/marketplace/actions/update-major-minor-semver
      - name: "Update major/minor release"
        uses: haya14busa/action-update-semver@v1
