name: "Submit release assets"

# The workflow below runs when the release event triggers when releases are created.
# For more information on the release event.
# See: [Events that trigger workflows](https://docs.github.com/en/actions/reference/events-that-trigger-workflows#release)

on:
  release:
    types:
      - created
      - edited

jobs:
  release-linux:
    # The the release job will only run if a release is created or if the latest release is edited/updated
    if: ${{ github.event.action == 'created' || ( github.event.action == 'edited' && github.event.release.tag_name == 'latest' ) }}
    name: "Publish Linux packages"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64
        goos: [linux]
        goarch: ["386", amd64, arm64]

    permissions:
      contents: write
      packages: write
      pull-requests: write

    steps:
    
      # See: https://github.com/marketplace/actions/checkout
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - uses: ./.github/actions/publish-package
        with:
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          extension: ""

  release-macos:
    # The the release job will only run if a release is created or if the latest release is edited/updated
    if: ${{ github.event.action == 'created' || ( github.event.action == 'edited' && github.event.release.tag_name == 'latest' ) }}
    name: "Publish macOS packages"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # build and publish in parallel: darwin/amd64, darwin/arm64
        goos: [darwin]
        goarch: [amd64, arm64]

    permissions:
      contents: write
      packages: write
      pull-requests: write

    steps:
    
      # See: https://github.com/marketplace/actions/checkout
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - uses: ./.github/actions/publish-package
        with:
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          extension: ""

  release-windows:
    # The the release job will only run if a release is created or if the latest release is edited/updated
    if: ${{ github.event.action == 'created' || ( github.event.action == 'edited' && github.event.release.tag_name == 'latest' ) }}
    name: "Publish Windows packages"
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # build and publish in parallel: windows/386, windows/amd64
        goos: [windows]
        goarch: ["386", amd64]

    permissions:
      contents: write
      packages: write
      pull-requests: write

    steps:
    
      # See: https://github.com/marketplace/actions/checkout
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - uses: ./.github/actions/publish-package
        with:
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          extension: ".exe"